export const LOAD_ALL_BOOKS = 'LOAD_ALL_BOOKS';
export const LOAD_SEARCH_BOOKS = 'LOAD_SEARCH_BOOKS';

export const LOAD_ALL_COMMENTS = 'LOAD_ALL_COMMENTS';
export const INSERT_COMMENTS = 'INSERT_COMMENTS';
